# Generated by Django 6.0.3 on 2026-04-23 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='file_url',
            field=models.URLField(blank=True),
        ),
    ]
