# Generated by Django 6.0.3 on 2026-04-23 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_song_file_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='provider',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
