# Generated by Django 6.0.3 on 2026-04-23 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_song_timestamps'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('genre', models.CharField(blank=True, max_length=100)),
                ('mood', models.CharField(blank=True, max_length=100)),
                ('occasion', models.CharField(blank=True, max_length=100)),
                ('singer_style', models.CharField(blank=True, max_length=100)),
                ('topic', models.CharField(blank=True, max_length=200)),
                ('provider', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('Success', 'Success'), ('Failed', 'Failed')], default='Success', max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('song', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generation_logs', to='music.song')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_logs', to='music.user')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
